### ISSUE TITLE
Be clear about time zones

### ISSUE THREAD

**Issue by black-puppydog** [chovanecm/sacredboard#49] opened 2017-06-13 09:02 UTC
The time displayed for last activity and the system time don't match. I suspect in the UI everything is displayed as GMT or some such?

![screenshot from 2017-06-13 10-31-30](https://user-images.githubusercontent.com/189241/27073277-943a208c-5023-11e7-9da2-1c41822c5b6d.png)

Might also be good to simply have a timestamp ("system time is currently $x") somewhere on the page, to avoid confusion.

I suspect that always using the local timezone for everything might be a good first approximation, assuming most people work locally.

**Comment by chovanecm** [comment] 2017-06-13 09:24
Hi, I know. There was a confusion in the beginning since Sacred was storing local time with UTC time zone. This has been fixed in Sacred but not yet in Sacredboard.
I'll have again some time to work on Sacredboard later this week.
(I'm closing this as it is a duplicate of #27 )

**Closed by chovanecm** 2017-06-13 09:24 UTC
Labels: duplicate
