### ISSUE TITLE
New column with results

### ISSUE THREAD

**Issue by szymonk92** [chovanecm/sacredboard#76] opened 2017-12-05 10:38 UTC
I would like to use Sacred with Keras and other ML tools for prototyping. Ideally would be to see the column with the results so I know which experiment is the most interesting for me.

**Comment by chovanecm** [comment] 2017-12-11 19:22
Hi,
there is a column with results visible in Sacredboard, isn't it?
Best
Martin

**Comment by chovanecm** [comment] 2018-03-23 19:05
Possibly a duplicate of #63.

**Closed by chovanecm** 2018-03-23 19:05 UTC
