### ISSUE TITLE
greenlet

### ISSUE THREAD

**Issue by SumNeuron** [chovanecm/sacredboard#110] opened 2019-03-01 14:05 UTC
```
sacredboard -F experiments/test/
Traceback (most recent call last):
  File "/anaconda3/bin/sacredboard", line 10, in <module>
    sys.exit(run())
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/sacredboard/bootstrap.py", line 111, in run
    version = Sacredboard.get_version()
  File "/anaconda3/lib/python3.6/site-packages/sacredboard/app/sacredboard.py", line 13, in get_version
    version = pkg_resources.require("sacredboard")[0].version
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (greenlet 0.4.13 (/anaconda3/lib/python3.6/site-packages), Requirement.parse('greenlet>=0.4.14; platform_python_implementation == "CPython"'), {'gevent'})


```

```
pip install sacredboard
Requirement already satisfied: sacredboard in /anaconda3/lib/python3.6/site-packages (0.4.2)
Requirement already satisfied: pymongo in /anaconda3/lib/python3.6/site-packages (from sacredboard) (3.7.2)
Requirement already satisfied: simplejson in /anaconda3/lib/python3.6/site-packages (from sacredboard) (3.16.0)
Requirement already satisfied: gevent in /anaconda3/lib/python3.6/site-packages (from sacredboard) (1.3.7)
Requirement already satisfied: click in /anaconda3/lib/python3.6/site-packages (from sacredboard) (7.0)
Requirement already satisfied: flask in /anaconda3/lib/python3.6/site-packages (from sacredboard) (1.0.2)
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython" (from gevent->sacredboard)
Requirement already satisfied: Werkzeug>=0.14 in /anaconda3/lib/python3.6/site-packages (from flask->sacredboard) (0.14.1)
Requirement already satisfied: Jinja2>=2.10 in /anaconda3/lib/python3.6/site-packages (from flask->sacredboard) (2.10)
Requirement already satisfied: itsdangerous>=0.24 in /anaconda3/lib/python3.6/site-packages (from flask->sacredboard) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /anaconda3/lib/python3.6/site-packages (from Jinja2>=2.10->flask->sacredboard) (1.1.1)
Installing collected packages: greenlet
  Found existing installation: greenlet 0.4.13
Cannot uninstall 'greenlet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by chovanecm** [comment] 2019-03-06 10:27
I assume you are using Anaconda on Linux.
I just tried to reproduce the issue by running a vanilla anaconda distribution in docker, installing and running sacredboard and I observed absolutely no problems.
It looks like you may have greenlet already installed using another tool than pip.

You can try some tips here: https://github.com/pypa/pip/issues/5247
or just create a new conda environment with ```conda -n create envname```, switch to it, and install sacredboard there.

But as this seems not to be caused by Sacredboard itself, I am closing the issue for now.

**Closed as completed by chovanecm** 2019-03-06 10:27 UTC
